### ISSUE TITLE
Using this with webpack?

### ISSUE THREAD

**Issue by acorncom** [deployjs/webpack-build#1]
Howdy, I've got a client app that needs a good deploy system and we're considering using DeployJS. Is there some way we can help get this plugin going? Any pointers on places that still need ironing out?

**Comment by duizendnegen** [comment]
I'm using this in production for deploying Webpack (both through `ng build` and through the regular Webpack flow). What's your deploy target? We deploy to AWS S3.
I'd be happy to help you land this.

**Comment by acorncom** [comment]
Thanks @duizendnegen, we're still exploring things and the client may not even work on deploying to a CDN just yet 😱 Will be in touch if we need a hand. Thanks!
